
all: sum_digits stocks_for stocks_do stocks_while prime


sum_digits: sum_digits.c
	  gcc -g -Wall -o sum_digits.x sum_digits.c

stocks_for: stocks_for.c
	  gcc -g -Wall -o stocks_for.x stocks_for.c
	  
stocks_do: stocks_do.c
	  gcc -g -Wall -o stocks_do.x stocks_do.c
	  
stocks_while: stocks_while.c
	  gcc -g -Wall -o stocks_while.x stocks_while.c

prime: prime.c
	  gcc -g -Wall -o prime.x prime.c
	  


 clean: 
	rm prime.x sum_digits.x stocks_do.x stocks_while.x stocks_for.x  
